version: '3.8'

services:
  db1:
    image: postgres:14.5
    environment:
      POSTGRES_DB: khamid_214
      POSTGRES_USER: khamid_214
      POSTGRES_PASSWORD: khamid_214
    volumes:
      - ./docker_sql_scripts/create_db1.sql:/docker-entrypoint-initdb.d/create_db.sql
      - ./docker_sql_scripts/fill_db1.sql:/docker-entrypoint-initdb.d/fill_db.sql
    ports:
      - "5432:5432"

  db2:
    image: postgres:14.5
    environment:
      POSTGRES_DB: khamid_214
      POSTGRES_USER: khamid_214
      POSTGRES_PASSWORD: khamid_214
    volumes:
      - ./docker_sql_scripts/create_db2.sql:/docker-entrypoint-initdb.d/create_db.sql
      - ./docker_sql_scripts/fill_db2.sql:/docker-entrypoint-initdb.d/fill_db.sql
    ports:
      - "5433:5432"
